### ISSUE TITLE
Add dump

### ISSUE THREAD

**Issue by BrunoSalerno** [citylines/citylines#107]
With only one city and no users

**Comment by alfredormz** [comment]
@BrunoSalerno I can take care of this issue if you want

**Comment by BrunoSalerno** [comment]
@alfredormz alright! nice :)

**Comment by BrunoSalerno** [comment]
I could use something like this: https://www.postgresql.org/about/news/postgresql-anonymizer-06-pseudonymization-and-improved-anonymous-exports-2017/ to anonymize the `users` table.
