### ISSUE TITLE
Deal with name and line's change

### ISSUE THREAD

**Issue by Kalepom** [citylines/citylines#141]
Some stations sometimes change their name, 
and the line riding a track can change throughout this tracks' life. 

Editor should be abale to show this name or lines change in the transit system history.

**Comment by BrunoSalerno** [comment]
@Kalepom Sorry for the late response! I find that this feature would be very interesting, and your proposed workaround could work. I'll try to do it!

**Comment by BrunoSalerno** [comment]
This should be implemented in the `Style` class.

* The `lines` attribute should have the years validity for each line (and the width or transport mode for each one of them).
* The `get` method should receive a `year` param.
* The lines should be filtered by current year.
* Only current lines should be displayed.
* The `line-offset` property should be set here, based on the current lines and their width/mode (not in the backend).

**Comment by BrunoSalerno** [comment]
Or/and maybe:
* The lines shown by line years range should be filtered the same way features are filtered by buildstart/opening.
* The offset should be calculated somehow in the Style class based on the visible lines at that moment.
