### ISSUE TITLE
Add URL share button

### ISSUE THREAD

**Issue by BrunoSalerno** [citylines/citylines#178]
This button should use the fa icon `fa-share-alt`, and it should be present both in city-view and in city-comparison components.

**Comment by christaylor19** [comment]
Which button?

**Comment by BrunoSalerno** [comment]
@christaylor19 there is no button yet. There should be some kind of button (or link), with the fa-share-alt icon (without text), somewhere in the city-view and in the city-comparison components.
For example, a suitable place may be next to the compare link (to the right), here:

<img width="276" alt="Captura de Pantalla 2019-12-01 a la(s) 17 31 30" src="https://user-images.githubusercontent.com/6061036/69916875-8dfff800-1460-11ea-8e2d-161182d4bcee.png">

It should be something like `<i className="fas fa-share-alt">`, wrapped by an anchor tag (or button). There might be already in npm a component for sharing in the social media. So the link/button should open this component (maybe a popup?) and from there the user should be able to share the current URL.
