### ISSUE TITLE
Link to /data from each city

### ISSUE THREAD

**Issue by BrunoSalerno** [citylines/citylines#232]
From the city view screen, in addition to the existing menu items, there should be a link that points to the Data screen. The label could be "Data". The URL should be something like `/data?city=buenos_aires#city`. The hash (`#city`) refers to the last section of the page, where there is a select control to choose the city, which should be the city passed in the `city` param from the query.

Things to consider:
* The implementation of the hash can be similar [to the one in the Terms component](https://github.com/citylines/citylines/blob/6081302d202c8c71c6713545d24759becd6f88f1/client/src/components/terms.js#L17-L29).
* All the new text has to be i18nized. New entries have to be added to the files in `api/config/locales`.

**Comment by christaylor19** [comment]
@BrunoSalerno Just to clear some terminology up here, does this Issue refer to adding a new link on each City page which links to the Data page with a pre-selected option in the "Data by city" dropdown? 

<img width="721" alt="Untitled" src="https://user-images.githubusercontent.com/10745832/95692424-92b74000-0c1d-11eb-9e94-30712bfd7c85.png">

**Comment by BrunoSalerno** [comment]
@christaylor19 yes, exactly!
